### ISSUE TITLE
Wikibase docker build calls composer but it doesn't exist

### ISSUE THREAD

**Issue by tarrow** [addshore/wikibase-docker#1]
Step 6/8 : RUN cd /Wikibase && composer install --no-dev
 ---> Running in 3b04f6c69876
/bin/sh: 1: composer: not found
ERROR: Service 'wikibase' failed to build: The command '/bin/sh -c cd /Wikibase && composer install --no-dev' returned a non-zero code: 127

**Comment by addshore** [comment]
Appears resolved to me
